repository:
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  default_branch: main

  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: '#FF0000'
  - name: feature
    color: '#0000FF'

branches:

  - name: main
    protection:

      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true

      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: false
        contexts: []

      enforce_admins: false
