name: add-to-project

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

permissions: {}

env:
  GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  PROJECT_OWNER: ntnn
  PROJECT_ID: PVT_kwHOAKBvfc4BRoCe
  STATUS_FIELD: PVTSSF_lAHOAKBvfc4BRoCezg_ZjNI
  STATUS_OPT_IN_REVIEW: df73e18b
  STATUS_OPT_KEEPING_TAGS: 6aadb620
  STATUS_OPT_REVIEWING: 63b8733f

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ./add-to-project.bash all
