name: add-to-project

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

permissions: {}

env:
  GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  PROJECT_OWNER: ntnn
  PROJECT_ID: PVT_kwHOAKBvfc4BRoCe

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ./add-to-project.bash all
