name: add-to-project

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

permissions: {}

env:
  GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  PROJECT_OWNER: ntnn
  PROJECT_ID: PVT_kwHOAKBvfc4BRoCe

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: bash ./add-to-project.bash
